Allow read-only access to /run/media by defualt
flathub/dev.bsnes.bsnes pull request #11
Opened 2022-10-31 22:04 UTC by YaBoiBurner

Added access to `/run/media` by default, so users who aren't familiar with flatpak aren't confused if they can't find ROMs they're storing on an external drive.

My main interest is making sure that the steam deck's SD card can be read by default, since I've seen someone confused that they couldn't find their ROMs on that. So this could be reduced down to `/run/media/mmcblk0p1:ro` if that's preferable.

2022-11-01 00:05 UTC, Screwtapello commented
By default, bsnes tries to store game saves beside the original ROM. If the drive is mounted read-only, is that going to cause problems? Or does Flatpak have some clever overlay filesystem that ensures everything bsnes writes gets stored somewhere else?

2022-11-01 08:52 UTC, ghisvail commented
I guess it would have to be exposed to the sandbox as read-write because of
the save game feature.

2022-11-01 13:36 UTC, YaBoiBurner commented
If it's being exposed read-write I'd rather limit this to just the steam deck's SD card then
I'll switch it to that a bit later today

2022-11-03 17:39 UTC, ghisvail requested changes
This should cover most use cases.

2022-11-03 17:39 UTC, ghisvail commented on dev.bsnes.bsnes.yaml
> +  - --filesystem=/run/media/mmcblk0p1
I don't think `bsnes` will ever reach a state where restricted sandboxing rules really make sense. Most traditional emulators use these set of restrictions. Let's align to them.

```suggestion
  - --filesystem=home
  - --filesystem=/media
  - --filesystem=/run/media
```

2022-11-03 20:56 UTC, ghisvail approved these changes

2022-11-03 20:57 UTC, merged